# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: TypeScript build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Setup Node.js
      uses: actions/setup-node@v2.1.4
      with:
        node-version: 12
    - name: Building Typescript
      uses: FuLagann/tsc-build-push@v1
      with:
        user-name: "actions-user"
        user-email: "action@github.com"
        message: "Automatically built typescript"
        directories: ./browser, ./commonjs
